model: edm
# model_parameters:
ckp_path: pretrained/edm-cifar10-32x32-uncond-vp.pkl
solver_name: uni_pc
unipc_variant: bh1
steps: 10
order: 2
time_mode: lambda

# training_parameters:
seed: 0
log_path: all_logs/cifar10_logs/
data_dir: train_data/train_data_cifar
win_rate: 0.5
prior_bound: 1.0
fix_bound: false
loss_type: LPIPS
main_train_batch_size: 2
main_valid_batch_size: 150
num_train: 50
num_valid: 50
training_rounds_v1: 2
training_rounds_v2: 5
shift_lr: null
lr_time_1: 0.005
lr_time_2: 0.1
min_lr_time_1: 0.00005
min_lr_time_2: 0.000001
momentum_time_1: 0.9
weight_decay_time_1: 0.0
shift_lr_decay: 0.5
lr_time_decay: 0.8
patient: 5
lr2_patient: 5
no_v1: false
visualize: true

# testing_parameters:
learn: false
load_from: null
skip_type: null
num_multi_steps_fid: null
fid_folder: all_fids/cifar10_fids/
sampling_batch_size: 150
sampling_seed: 0
ref_path: fid-refs/cifar10-32x32.npz
total_samples: 50000
save_png: false
save_pt: true